
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.Datos;

/** CUP generated class containing symbol constants. */
public class simDatos {
  /* terminals */
  public static final int PSRegistro = 8;
  public static final int llaveC = 7;
  public static final int PSClaves = 9;
  public static final int llaveA = 6;
  public static final int coma = 2;
  public static final int cadena = 10;
  public static final int decimal = 12;
  public static final int EOF = 0;
  public static final int entero = 11;
  public static final int error = 1;
  public static final int corC = 5;
  public static final int corA = 4;
  public static final int igual = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "igual",
  "corA",
  "corC",
  "llaveA",
  "llaveC",
  "PSRegistro",
  "PSClaves",
  "cadena",
  "entero",
  "decimal"
  };
}

