
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.reportes;

/** CUP generated class containing symbol constants. */
public class simReportes {
  /* terminals */
  public static final int menorigual = 10;
  public static final int PSGraficar = 20;
  public static final int cadena = 24;
  public static final int PSCadena = 23;
  public static final int decimal = 26;
  public static final int coma = 2;
  public static final int PSArchivo = 13;
  public static final int dobleigual = 12;
  public static final int ptcoma = 3;
  public static final int PSLeerArchivo = 15;
  public static final int mayorigual = 9;
  public static final int igual = 4;
  public static final int menorque = 8;
  public static final int EOF = 0;
  public static final int negacion = 11;
  public static final int PSNumerico = 21;
  public static final int mayorque = 7;
  public static final int error = 1;
  public static final int parC = 6;
  public static final int PSContar = 16;
  public static final int parA = 5;
  public static final int PSObtenersi = 18;
  public static final int entero = 25;
  public static final int PSPromedio = 22;
  public static final int PSImprimir = 19;
  public static final int PSSumar = 14;
  public static final int PSContarsi = 17;
  public static final int identificador = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "ptcoma",
  "igual",
  "parA",
  "parC",
  "mayorque",
  "menorque",
  "mayorigual",
  "menorigual",
  "negacion",
  "dobleigual",
  "PSArchivo",
  "PSSumar",
  "PSLeerArchivo",
  "PSContar",
  "PSContarsi",
  "PSObtenersi",
  "PSImprimir",
  "PSGraficar",
  "PSNumerico",
  "PSPromedio",
  "PSCadena",
  "cadena",
  "entero",
  "decimal",
  "identificador"
  };
}

